[package]
name = "template-cli-rs"
version = "0.1.0"
edition = "2021"
authors = ["rinse <rinse418@gmail.com>"]
description = "Template for a CLI app"

[dependencies]
anyhow = "1.0.86"
clap = { version = "4.5.8", features = ["derive"] }
thiserror = "1.0.61"
